services:
  - type: web
    name: truonghoc-api
    env: java
    repo: https://github.com/dao24092004/StudentApp
    branch: main
    buildCommand: mvn clean package
    startCommand: java -jar target/TruongHoc-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JWT_SECRET
        value: your-very-long-and-random-secret-key-1234567890abcdef
      - key: JWT_ACCESS_TOKEN_EXPIRATION
        value: 3600000
      - key: JWT_REFRESH_TOKEN_EXPIRATION
        value: 604800000
      - key: SPRING_WEB_CORS_ALLOWED_ORIGINS
        value: http://localhost:3000