version: "3.8"

services:
  db:
    image: postgres:15.0
    environment:
      POSTGRES_USER: studentApp
      POSTGRES_PASSWORD: 1234$
      POSTGRES_DB: student_db
    ports:
      - "5432:5432"
    restart: always
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6479:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: