name: CI Pipeline
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn clean install
    - name: Run Unit Tests
      run: mvn test
    - name: Run SpotBugs
      run: mvn spotbugs:check
    - name: Run Dependency Check
      run: mvn dependency-check:check